#!/usr/bin/python3
###
### Author: rdt12@psu.edu
### Date: Sep 3, 2020
### Desc: In a loop, connect to the HOP server and write metrics to the influx server.
###       Metrics include:
###
###           time to run kafkacat
###           hearbeats since last loop
###           difference between hearbeat timestamp and now
###
from optparse import OptionParser
import Utils as ut
import HeartUtils as hu
import sys
import os
import time

## Line buffer stdout and stderr
sys.stdout = os.fdopen(sys.stdout.fileno(), 'w', buffering=1)
sys.stderr = os.fdopen(sys.stderr.fileno(), 'w', buffering=1)
##
## Parse options.
##
cHelp  = "SCiMMA client configuration file"
sHelp  = "SCiMMA server URL"
sUrl   = "dev.hop.scimma.org:9092"
iUrl   = "http://influx.dev.hop.scimma.org:8010"
p = OptionParser(usage="Usage: %prog [options]")
p.add_option("",   "--scimma", dest="scimmaUrl", default=sUrl, help=sHelp)
p.add_option("-F", "--config", dest="scimmaConfFile", default="~/shared/kafkacat.conf", help=cHelp)
(o, a) = p.parse_args()

scimmaUrl      = o.scimmaUrl
scimmaConfFile = os.path.expanduser(o.scimmaConfFile)
influxUrl      = iUrl
influxDb       = "hop"
print("hopBeatMon starting")
print("SCiMMA server URL:  %s"   % scimmaUrl)
print("SCiMMA config file: %s\n" % scimmaConfFile)

lastBeat = 0
while (True):
     ok, now, kafkaTime, curBeat, beatlag = hu.getStats(scimmaUrl)
     if ((lastBeat > 0) or (ok == 0)):
          hu.writeStats(influxUrl, influxDb, ok, now, kafkaTime, lastBeat, curBeat, beatlag)
     lastBeat = curBeat
     print("Sleeping...")
     time.sleep(60)
exit(0)
